export const SET_SELECTED_FILTER = "SET_SELECTED_FILTER";
export const SET_HIKING_GEAR = "SET_HIKING_GEAR";
export const INCREMENT_OPENED_INDEX = "INCREMENT_OPENED_INDEX";
export const DECREMENT_OPENED_INDEX = "DECREMENT_OPENED_INDEX";
export const SET_OPENED_INDEX = "SET_OPENED_INDEX";
